---
- name: Deploy Application with Docker
  hosts: dev
  user: ansible
  become: yes
  connection: ssh
  gather_facts: no
  tasks:

    - name: Remove old Docker container if exists
      command: docker rm -f web
      ignore_errors: yes

    - name: Remove old Docker image if exists
      command: docker rmi -f prajwal0303/webapp:latest
      ignore_errors: yes

    - name: Log in to Docker Hub
      command: echo "ABD@2003" | docker login -u prajwal0303 --password-stdin

    - name: Pull Docker Image from Docker Hub
      command: docker pull prajwal0303/webapp:latest

    - name: Run Docker Container
      command: docker run -it -d --name web -p 8081:8080 prajwal0303/webapp:latest


